import type { Event, VendorProfile, Bid, Booking, Review } from '@/types'

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-1',
    consumer_id: 'user-1',
    title: 'Priya & Karthik Wedding',
    type: 'wedding',
    date: '2026-11-15',
    duration_hours: 8,
    venue_name: 'The Leela Palace',
    venue_address: 'MRC Nagar, Chennai 600 028',
    lat: 13.0194,
    lng: 80.2707,
    guest_count: 350,
    budget_min: 500000,
    budget_max: 1200000,
    needed_categories: ['catering', 'photography', 'decoration', 'entertainment', 'av_production'],
    notes: 'Tamil Brahmin wedding. Lunch + dinner. No DJ, live nadaswaram required.',
    visibility: 'public',
    bid_deadline: '2026-10-01T18:00:00Z',
    status: 'open',
    bids_count: 7,
    created_at: '2026-05-19T10:00:00Z',
  },
  {
    id: 'evt-2',
    consumer_id: 'user-2',
    title: 'TechCorp Annual Day 2026',
    type: 'awards_night',
    date: '2026-12-20',
    duration_hours: 5,
    venue_name: 'ITC Grand Chola Ballroom',
    venue_address: 'Mount Road, Chennai 600 002',
    lat: 13.0569,
    lng: 80.2425,
    guest_count: 200,
    budget_min: 200000,
    budget_max: 500000,
    needed_categories: ['catering', 'av_production', 'decoration', 'photography'],
    visibility: 'public',
    bid_deadline: '2026-11-15T18:00:00Z',
    status: 'bids_received',
    bids_count: 4,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'evt-3',
    consumer_id: 'user-3',
    title: "Aarav's 5th Birthday Party",
    type: 'birthday',
    date: '2026-06-10',
    duration_hours: 3,
    venue_address: 'Anna Nagar, Chennai 600 040',
    lat: 13.0878,
    lng: 80.2143,
    guest_count: 60,
    budget_min: 15000,
    budget_max: 35000,
    needed_categories: ['catering', 'decoration', 'entertainment', 'cake_desserts'],
    notes: 'Superhero theme. Soft drinks and snacks only, no full meals.',
    visibility: 'public',
    bid_deadline: '2026-05-28T18:00:00Z',
    status: 'open',
    bids_count: 2,
    created_at: '2026-05-19T14:00:00Z',
  },
]

export const MOCK_VENDORS: VendorProfile[] = [
  {
    id: 'vendor-1',
    user_id: 'user-v1',
    business_name: 'Sree Caterers',
    tagline: 'Authentic Tamil Nadu flavors, flawlessly served',
    about: 'Family-run catering business with 18 years of experience across Chennai. Specialize in Tamil Brahmin cuisine, South Indian buffets, and North Indian fusion.',
    categories: ['catering'],
    gstin: '33AABCS1234M1Z5',
    pan: 'AABCS1234M',
    is_kyc_verified: true,
    is_backup_pool: true,
    subscription_tier: 'pro',
    service_radius_km: 30,
    lat: 13.0418,
    lng: 80.2341,
    city: 'Chennai',
    address: 'T. Nagar, Chennai 600 017',
    avg_rating: 4.8,
    total_reviews: 126,
    total_events: 312,
    repeat_booking_count: 89,
    response_time_hours: 1.5,
    reliability_score: 96,
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800', type: 'image', caption: 'Grand wedding buffet', event_type: 'wedding' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800', type: 'image', caption: 'Corporate lunch spread', event_type: 'corporate' },
    ],
    packages: [
      {
        id: 'pkg-1',
        name: 'Wedding Grand Package',
        description: 'Full-day catering for 200-500 guests. South Indian or North Indian menu.',
        price: 185000,
        includes: ['Breakfast', 'Lunch', 'Dinner', 'Welcome drinks', 'Serving staff (1 per 25 guests)', 'Crockery & cutlery', 'Setup & cleanup'],
        excludes: ['Venue charges', 'Gas/fuel surcharge for >50km'],
        min_advance_days: 30,
        max_guests: 500,
      },
    ],
    availability_blocked: [],
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'vendor-2',
    user_id: 'user-v2',
    business_name: 'Pixel Perfect Studios',
    tagline: 'Your story, frame by frame',
    about: 'Award-winning photography and videography studio. 10+ years, 600+ weddings, events across Tamil Nadu.',
    categories: ['photography'],
    is_kyc_verified: true,
    is_backup_pool: false,
    subscription_tier: 'growth',
    service_radius_km: 50,
    lat: 13.0061,
    lng: 80.2572,
    city: 'Chennai',
    address: 'Adyar, Chennai 600 020',
    avg_rating: 4.9,
    total_reviews: 204,
    total_events: 628,
    repeat_booking_count: 143,
    response_time_hours: 2,
    reliability_score: 99,
    portfolio: [
      { id: 'pp1', url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800', type: 'image', caption: 'Wedding candid', event_type: 'wedding' },
    ],
    packages: [
      {
        id: 'pkg-photo-1',
        name: 'Full-Day Wedding Coverage',
        description: '12 hours, 2 photographers, 1 videographer. Cinematic highlight reel + 1000 edited photos.',
        price: 65000,
        includes: ['2 photographers', '1 videographer', '12-hour coverage', '1000+ edited photos', 'Cinematic highlight reel (5 min)', 'Same-day slideshow', 'Online gallery delivery in 30 days'],
        excludes: ['Drone footage', 'Pre-wedding shoot', 'Albums/prints'],
        min_advance_days: 45,
      },
    ],
    availability_blocked: ['2026-11-14', '2026-11-20'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'vendor-3',
    user_id: 'user-v3',
    business_name: 'Bloom & Drape Décor',
    tagline: 'Transforming spaces into memories',
    about: 'Specialist in floral mandaps, stage decoration, and immersive event design.',
    categories: ['decoration'],
    is_kyc_verified: true,
    is_backup_pool: true,
    subscription_tier: 'pro',
    service_radius_km: 25,
    lat: 13.0827,
    lng: 80.2707,
    city: 'Chennai',
    address: 'Velachery, Chennai 600 042',
    avg_rating: 4.7,
    total_reviews: 88,
    total_events: 215,
    repeat_booking_count: 62,
    response_time_hours: 3,
    reliability_score: 94,
    portfolio: [
      { id: 'bd1', url: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', type: 'image', caption: 'Grand floral mandap', event_type: 'wedding' },
    ],
    packages: [
      {
        id: 'pkg-dec-1',
        name: 'Wedding Premium Décor',
        description: 'Full venue décor with grand floral mandap, stage, entrance, and table centers.',
        price: 120000,
        includes: ['Floral mandap (12x12 ft)', 'Stage backdrop', 'Entrance arch', 'Table centerpieces (20 tables)', 'Aisle decoration', 'Setup + teardown'],
        excludes: ['LED uplighting', 'Ceiling draping'],
        min_advance_days: 21,
      },
    ],
    availability_blocked: [],
    created_at: '2026-01-20T00:00:00Z',
  },
]

export const MOCK_BIDS: Bid[] = [
  {
    id: 'bid-1',
    event_id: 'evt-1',
    vendor_id: 'vendor-1',
    vendor: MOCK_VENDORS[0],
    category: 'catering',
    service_description: 'Full-day catering for 350 guests. Tamil Brahmin veg menu (Iyer style). Breakfast + Lunch + Dinner + Welcome drinks.',
    price: 210000,
    includes: ['Breakfast for 350', 'Lunch for 350', 'Dinner for 350', 'Welcome drinks', 'Serving staff (14 staff)', 'Crockery & cutlery'],
    excludes: ['Gas surcharge if outside Chennai corporation', 'Extra dishes beyond agreed menu'],
    advance_percent: 30,
    message: 'We have handled 40+ Tamil Brahmin weddings. References available. Happy to do a trial tasting.',
    portfolio_samples: ['https://images.unsplash.com/photo-1555244162-803834f70033?w=400'],
    status: 'pending',
    expires_at: '2026-09-28T18:00:00Z',
    created_at: '2026-05-19T11:30:00Z',
  },
  {
    id: 'bid-2',
    event_id: 'evt-1',
    vendor_id: 'vendor-2',
    vendor: MOCK_VENDORS[1],
    category: 'photography',
    service_description: 'Full wedding day coverage — from muhurtham to reception. 3 photographers + 1 drone operator.',
    price: 85000,
    includes: ['3 photographers', '1 drone operator', 'Cinematic reel (8 min)', '1500+ edited photos', 'Online gallery', 'Same-day teaser (30 photos)'],
    excludes: ['Pre-wedding shoot', 'Physical albums'],
    advance_percent: 25,
    message: 'We specialize in Tamil weddings and have captured 200+ weddings at The Leela and similar venues.',
    portfolio_samples: ['https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=400'],
    status: 'pending',
    expires_at: '2026-09-28T18:00:00Z',
    created_at: '2026-05-19T12:00:00Z',
  },
]
